source 'https://rubygems.org'

ruby '2.2.0'
gem 'thin' # or mongrel
gem 'rake'
gem 'slim'
gem 'padrino-angularjs'
gem 'padrino-sprockets'
gem 'coffee-script'

gem 'cucumber'
gem 'capybara'
gem 'poltergeist'
gem 'capybara-angular'
gem 'rspec_junit_formatter'
gem 'rspec'
gem 'simplecov', "0.8.0.pre"
gem 'guard'   
gem 'guard-rspec'
gem 'byebug'


gem 'erubis', '~> 2.7.0'
gem 'padrino', '0.11.2'
gem 'oj'